default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: team_project_51_development

test:
  <<: *default
  database: team_project_51_test

production:
  <<: *default
  database: team_project_production
  username: team_project
  password: <%= ENV['TEAM_PROJECT_DATABASE_PASSWORD'] %>
